[build]
  # Build command for Expo web
  command = "cd LevityLoyaltyExpo && npm ci && npm run web:build"

  # Directory to publish (Expo web build output)
  publish = "LevityLoyaltyExpo/dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Expo environment variables
  EXPO_PUBLIC_API_URL = "https://levity-loyalty-mobile.netlify.app"
  NODE_ENV = "production"

  # Build optimization
  CI = "true"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/_expo/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# API proxy (if needed for CORS)
[[redirects]]
  from = "/api/*"
  to = "https://levity-loyalty-api.netlify.app/api/:splat"
  status = 200
  force = true
